%include 'sys.ins.pas';
%include 'util.ins.pas';
%include 'string.ins.pas';
%include 'file.ins.pas';
%include 'img.ins.pas';
%include 'vect.ins.pas';
%include 'ray_kernel.ins.pas';
%include 'ray.ins.pas';
%include 'ray_type1.ins.pas';
